version: "3"

services:
  nginx:
    image: nginx:latest
    container_name: ecat_nginx
    ports:
        - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./operands:/var/www/html
    depends_on:
      - php

  php:
    image: php:5.6-fpm-jessie
    container_name: ecat_fpm
    volumes: 
      - ./src/:/var/www/html
      - ./storage:/var/www/storage